apiVersion: v1
kind: Service
metadata:
    name: "ccalliancecluster-fc55"
    labels:
        app: "ccalliancecluster-fc55"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "ccalliancecluster-fc55"